### ISSUE TITLE
Creating sketch from circle offsets sketch

### ISSUE THREAD

**Issue by marsfan** [mwganson/MeshRemodel#32]
Been playing around with this workbench, as it makes some of the stuff I do much easier, however, I cannot seem to get the creation of a sketch from circles/shapes/lines/etc to work properly, it shifts the sketch after creating it. 

In the example below, I created the points object from the mesh, then create a circle from the points object. Then I `ctrl+click` on the `Create New Empty Sketch` button to convert the circle to a sketch, and it properly creates a sketch, but then makes the sketch jump away from where I want it. 

![2020-11-29_15-17-01](https://user-images.githubusercontent.com/9311953/100555114-9e56d880-3256-11eb-9d65-bcba8a21b167.gif)

The reason that I do not just create the extrusions from the circles is that these models are not high precision, and I often have to adjust dimensions a little bit (such as from 2.7328399999 to 2.75).

**Comment by mwganson** [comment]
This is a known issue.  The circle object has a radius property which can be adjusted.  Another option is to select the 3 points and use the coplanar points object icon (alt + click) to create a sketch mapped to the plane defined by those 3 points and automatically include links to external geometry to the points in that plane.  Then use the circle tools in the sketcher to create the sketch using those external links.  After creating the elements you can delete the external links and then constrain the sketch after that.  You could also do something similar using shift + click on the create a sketch icon.  The difference is the sketch uses the first 3 selected points to map the sketch to that plane and adds all selected points as external geometry (as opposed to adding all the points in that plane).  The advantage is you can select only those points you want as links to external geometry and they need not all be on the same plane.

**Comment by Marsfan** [comment]
@Marsfan Cool. That's what I have been doing. I just wanted to make sure that this was added to the bug tracker. 

I suspect that it might not be entirely this extension's fault, as I was having some similar issues in another workbench (I think it was the draft workbench)

**Comment by mwganson** [comment]
Right.  It uses Draft to Sketch, which is where the limitation comes in.
