### ISSUE TITLE
Once workbench is activated the toolbar won't go away

### ISSUE THREAD

**Issue by macdroid53** [mwganson/MeshRemodel#46]
Happened to be tinkering with this today and found that once I activated the workbench, the toolbar is ever present and doesn't go away once another workbench is selected.

It also does not show up in the right-click selection to turn off toolbars.

Back to normal after FC restart.

[code]
OS: Debian GNU/Linux 11 (bullseye) (XFCE/lightdm-xsession)
Word size of FreeCAD: 64-bit
Version: 0.21.0.31504 (Git)
Build type: Release
Branch: master
Hash: bb566c7777c5d41ae2adea5a5488528b8d1d0a6c
Python 3.9.2, Qt 5.15.2, Coin 4.0.0, Vtk 7.1.1, OCC 7.5.1
Locale: English/United States (en_US)
Installed mods: 
  * parts_library
  * kicadStepUpMod 10.16.8
  * Manipulator 1.4.9
  * PrefExtras
  * QuickMeasure 2022.10.28
  * MyDefaults 2022.9.15
  * ZolkoBase 0.0.1
  * DynamicData 2.46.0
  * fasteners 0.4.51
  * Nodes 0.1.36
  * MacMechX 2022.9.15
  * ExtremeProDark 2.6.4
  * ProDarkThemePreferencePack 1.0.0
  * fcgear 1.0.0
  * plugins
  * Pyramids-and-Polyhedrons
  * Defeaturing 1.2.0
  * Assembly4 0.12.5
  * MeshRemodel 1.8919.0
  * BaseTest 0.0.1
  * OpticsWorkbench 1.0.9
  * workfeature-macro
  * sheetmetal 0.2.60
  * A2plus 0.4.60g
  * CurvedShapes 1.0.4
  * BasicMech 0.0.1
  * Dracula 0.0.2
  * Curves 0.6.5
  * workfeature
  * toSketch 1.0.1
  * lattice2 1.0.0
[/code]

**Comment by mwganson** [comment]
[Settings ](https://github.com/mwganson/MeshRemodel#keep-toolbar-active)

**Comment by macdroid53** [comment]
Hmm...Never thought to look in the menu for settings. ;)
Thanks.

**Comment by luzpaz** [comment]
Is this still relevant ?

**Comment by mwganson** [comment]
I just pushed a new update to 1.10.34.  Now there is a dialog to ask the user whether to keep the toolbar active.  Closing issue.
